### ISSUE TITLE
cannot import after install

### ISSUE THREAD

**Issue by maxsiegel** [NicolasKuske/motivepy#46]
Hi,

Installation works as prescribed (except I used Miniconda instead of the system python, should this matter?) but when I import motive, I get this error:

```python
>>> import motive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "motive\__init__.py", line 3, in <module>
    from native import *
ImportError: No module named native
```

This is on Windows 10, 64 bit. Motive 1.10.3 (but also I had this problem with 1.9).

Thanks

**Comment by neuroneuro15** [comment]
Hi,
I see, this is a Python 2 vs 3 error (Relative vs Absolute Imports).  It should be changed to something like:

```python
from . import native
```
